# Generated by Django 4.2.6 on 2023-10-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_category_category_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
